<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="StatefulServiceClassService"
     targetNamespace="http://soap.stateful.pradipta.com/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soap.stateful.pradipta.com/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="StatefulSOAPService">
        <plnk:role name="StatefulServiceClassPortType" portType="tns:StatefulServiceClassPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soap.stateful.pradipta.com/" location="StatefulServiceClassPort.wsdl"/>
</wsdl:definitions>
