<wsdl:definitions
     name="DB_POLL_UPDT_SEQ_TBL"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorldSOA/DataBaseOperations/DB_POLL_UPDT_SEQ_TBL"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorldSOA/DataBaseOperations/DB_POLL_UPDT_SEQ_TBL"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_POLL_UPDT_SEQ_TBL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_POLL_UPDT_SEQ_TBL_plt" >
    <plt:role name="DB_POLL_UPDT_SEQ_TBL_role" >
      <plt:portType name="tns:DB_POLL_UPDT_SEQ_TBL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_POLL_UPDT_SEQ_TBL_plt" >
    <plt:role name="DB_POLL_UPDT_SEQ_TBL_role" >
      <plt:portType name="tns:DB_POLL_UPDT_SEQ_TBL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_POLL_UPDT_SEQ_TBL_plt" >
    <plt:role name="DB_POLL_UPDT_SEQ_TBL_role" >
      <plt:portType name="tns:DB_POLL_UPDT_SEQ_TBL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="DB_POLL_UPDT_SEQ_TBL_plt" >
    <plt:role name="DB_POLL_UPDT_SEQ_TBL_role" >
      <plt:portType name="tns:DB_POLL_UPDT_SEQ_TBL_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_POLL_UPDT_SEQ_TBL" schemaLocation="../Schemas/DB_POLL_UPDT_SEQ_TBL_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PollingTableCollection_msg">
        <wsdl:part name="PollingTableCollection" element="top:PollingTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_POLL_UPDT_SEQ_TBL_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:PollingTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
